# Generated by Django 3.1.7 on 2021-04-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210409_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveScanID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_data', models.CharField(max_length=100)),
                ('scan_website', models.TextField()),
                ('date', models.TextField()),
                ('email', models.TextField()),
                ('scan_type', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='userreport',
            name='date',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreport',
            name='scan_type',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserPortReport',
        ),
    ]
