# Generated by Django 3.1.7 on 2021-04-13 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210412_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='report_url',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreport',
            name='vulnerabilities_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserPortReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_data', models.CharField(max_length=100)),
                ('state', models.TextField()),
                ('date', models.TextField()),
                ('protocol', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
